POST http://192.168.1.2:8080/definitions/import?layerGroup=COMPOSER&tags=composer,hv,infrastructure
Content-Type: application/json

[
  {
    "classIds": "HVANSU",
    "styles": [
      {
        "styleId": "TEMPLATE",
        "styleType": "POINT",
        "description": "HVANSU_TEMPLATE",
        "defaultStyle": false,
        "attributes": [
          { "name": "classTemplate", "value": "true" }
        ],
        "iconUrl": "assets/app/img/map-markers/puc/CL_STRUCTURE_NODE/sostegno-AT.svg",
        "weight": 5,
        "color": "#FF0000"
      },
      {
        "styleId": "SEARCH_TEMPLATE",
        "styleType": "POINT",
        "description": "SEARCH_TEMPLATE",
        "defaultStyle": false,
        "attributes": [
          { "name": "searchClassTemplate", "value": "true" }
        ],
        "iconUrl": "assets/app/img/map-markers/puc/CL_STRUCTURE_NODE/sostegno-AT.svg",
        "weight": 5,
        "color": "#FFFFFF"
      },
      {
        "styleId": "HVANSU",
        "styleType": "POINT",
        "description": "HVANSU",
        "defaultStyle": false,
        "attributes": [],
        "color": "#ff0000",
        "iconUrl": "assets/app/img/map-markers/puc/CL_STRUCTURE_NODE/sostegno-AT.svg",
        "weight": 5
      },
      {
        "styleId": "HVANSU-editMode",
        "styleType": "POINT",
        "description": "HVANSU-editMode",
        "defaultStyle": false,
        "attributes": [],
        "color": "#999999",
        "iconUrl": "assets/app/img/map-markers/puc/CL_STRUCTURE_NODE/sostegno-AT.svg",
        "weight": 5
      },
      {
        "styleId": "HVANSU-dismantled",
        "styleType": "POINT",
        "description": "HVANSU-dismantled",
        "defaultStyle": false,
        "attributes": [],
        "color": "yellow",
        "iconUrl": "assets/app/img/map-markers/puc/CL_STRUCTURE_NODE/sostegno-AT.svg",
        "weight": 5
      },
      {
        "styleId": "HVANSU-outOfService",
        "styleType": "POINT",
        "description": "HVANSU-outOfService",
        "defaultStyle": false,
        "attributes": [],
        "color": "violet",
        "iconUrl": "assets/app/img/map-markers/puc/CL_STRUCTURE_NODE/sostegno-AT.svg",
        "weight": 5
      }
    ],
    "styleRules": [
      {
        "value": "HVANSU-editMode",
        "criteria": [
          {
            "field": "properties.editMode",
            "value": "true",
            "fieldType": "string",
            "operator": "=",
            "criteriaOperator": "AND"
          }
        ]
      },
      {
        "value": "HVANSU-dismantled",
        "criteria": [
          {
            "field": "properties.objectFormStatusIdPrefix",
            "value": "84",
            "fieldType": "number",
            "operator": "=",
            "criteriaOperator": "AND"
          }
        ]
      },
      {
        "value": "HVANSU-outOfService",
        "criteria": [
          {
            "field": "properties.objectFormStatusIdPrefix",
            "value": "86",
            "fieldType": "number",
            "operator": "=",
            "criteriaOperator": "AND"
          }
        ]
      },
      {
        "value": "HVANSU",
        "criteria": []
      }
    ],
    "sizeRules": [
      {
        "value": "24",
        "criteria": []
      }
    ],
    "labelRules": [],
    "tooltipRules": [
      {
        "value": "'<strong>'+context.feature.properties.pucId+' '+translate.instant(context.feature.properties.objectCode)+'</strong><p class=\"tooltip-line\">'+context.feature.properties.code+'</p><p class=\"tooltip-line\"> '+translate.instant(context.feature.properties.status)+'</p><p class=\"tooltip-line\"> '+translate.instant('HV Grid')+'</p>'",
        "criteria": []
      }
    ],
    "menuHeaderDataRules": []
  },
  {
    "classIds": "HUCNIN",
    "styles": [
      {
        "styleId": "TEMPLATE",
        "styleType": "POINT",
        "description": "HUCNIN_TEMPLATE",
        "defaultStyle": false,
        "attributes": [
          { "name": "classTemplate", "value": "true" }
        ],
        "iconUrl": "assets/app/img/map-markers/puc/CL_MANHOLE/pozzetto-at.svg",
        "color": "#FF0000"
      },
      {
        "styleId": "SEARCH_TEMPLATE",
        "styleType": "POINT",
        "description": "SEARCH_TEMPLATE",
        "defaultStyle": false,
        "attributes": [
          { "name": "searchClassTemplate", "value": "true" }
        ],
        "iconUrl": "assets/app/img/map-markers/puc/CL_MANHOLE/pozzetto-at.svg",
        "color": "#FFFFFF"
      },
      {
        "styleId": "HUCNIN",
        "styleType": "POINT",
        "description": "HUCNIN",
        "defaultStyle": false,
        "attributes": [],
        "color": "#ff0000",
        "iconUrl": "assets/app/img/map-markers/puc/CL_MANHOLE/pozzetto-at.svg"
      },
      {
        "styleId": "HUCNIN-editMode",
        "styleType": "POINT",
        "description": "HUCNIN-editMode",
        "defaultStyle": false,
        "attributes": [],
        "color": "#999999",
        "iconUrl": "assets/app/img/map-markers/puc/CL_MANHOLE/pozzetto-at.svg"
      },
      {
        "styleId": "HUCNIN-dismantled",
        "styleType": "POINT",
        "description": "HUCNIN-dismantled",
        "defaultStyle": false,
        "attributes": [],
        "color": "yellow",
        "iconUrl": "assets/app/img/map-markers/puc/CL_MANHOLE/pozzetto-at.svg"
      },
      {
        "styleId": "HUCNIN-outOfService",
        "styleType": "POINT",
        "description": "HUCNIN-outOfService",
        "defaultStyle": false,
        "attributes": [],
        "color": "violet",
        "iconUrl": "assets/app/img/map-markers/puc/CL_MANHOLE/pozzetto-at.svg"
      }
    ],
    "styleRules": [
      {
        "value": "HUCNIN-editMode",
        "criteria": [
          {
            "field": "properties.editMode",
            "value": "true",
            "fieldType": "string",
            "operator": "=",
            "criteriaOperator": "AND"
          }
        ]
      },
      {
        "value": "HUCNIN-dismantled",
        "criteria": [
          {
            "field": "properties.objectFormStatusIdPrefix",
            "value": "84",
            "fieldType": "number",
            "operator": "=",
            "criteriaOperator": "AND"
          }
        ]
      },
      {
        "value": "HUCNIN-outOfService",
        "criteria": [
          {
            "field": "properties.objectFormStatusIdPrefix",
            "value": "86",
            "fieldType": "number",
            "operator": "=",
            "criteriaOperator": "AND"
          }
        ]
      },
      {
        "value": "HUCNIN",
        "criteria": []
      }
    ],
    "sizeRules": [
      {
        "value": "24",
        "criteria": []
      }
    ],
    "labelRules": [],
    "tooltipRules": [
      {
        "value": "'<strong>'+context.feature.properties.pucId+' '+translate.instant(context.feature.properties.objectCode)+'</strong><p class=\"tooltip-line\">'+context.feature.properties.code+'</p><p class=\"tooltip-line\"> '+translate.instant(context.feature.properties.status)+'</p><p class=\"tooltip-line\"> '+translate.instant('HV Grid')+'</p>'",
        "criteria": []
      }
    ],
    "menuHeaderDataRules": []
  },
  {
    "classIds": "HVUCIA",
    "styles": [
      {
        "styleId": "TEMPLATE",
        "styleType": "LINE",
        "description": "HVUCIA_TEMPLATE",
        "defaultStyle": false,
        "attributes": [
          { "name": "classTemplate", "value": "true" }
        ],
        "iconUrl": "assets/app/img/map-markers/puc/LINE/line.svg",
        "color": "#FF0000",
        "weight": 2,
        "dashArray": "6,3"
      },
      {
        "styleId": "SEARCH_TEMPLATE",
        "styleType": "LINE",
        "description": "SEARCH_TEMPLATE",
        "defaultStyle": false,
        "attributes": [
          { "name": "searchClassTemplate", "value": "true" }
        ],
        "iconUrl": "assets/app/img/map-markers/puc/LINE/line.svg",
        "color": "#FFFFFF",
        "weight": 2,
        "dashArray": "6,3"
      },
      {
        "styleId": "HVUCIA",
        "styleType": "LINE",
        "description": "HVUCIA",
        "defaultStyle": false,
        "attributes": [],
        "color": "#ff0000",
        "iconUrl": "assets/app/img/map-markers/puc/LINE/line.svg",
        "weight": 2,
        "dashArray": "6,3"
      },
      {
        "styleId": "HVUCIA-editMode",
        "styleType": "LINE",
        "description": "HVUCIA-editMode",
        "defaultStyle": false,
        "attributes": [],
        "color": "#999999",
        "iconUrl": "assets/app/img/map-markers/puc/LINE/line.svg",
        "weight": 2,
        "dashArray": "6,3"
      },
      {
        "styleId": "HVUCIA-dismantled",
        "styleType": "LINE",
        "description": "HVUCIA-dismantled",
        "defaultStyle": false,
        "attributes": [],
        "color": "yellow",
        "iconUrl": "assets/app/img/map-markers/puc/LINE/line.svg",
        "weight": 2,
        "dashArray": "6,3"
      },
      {
        "styleId": "HVUCIA-outOfService",
        "styleType": "LINE",
        "description": "HVUCIA-outOfService",
        "defaultStyle": false,
        "attributes": [],
        "color": "violet",
        "iconUrl": "assets/app/img/map-markers/puc/LINE/line.svg",
        "weight": 2,
        "dashArray": "6,3"
      }
    ],
    "styleRules": [
      {
        "value": "HVUCIA-editMode",
        "criteria": [
          {
            "field": "properties.editMode",
            "value": "true",
            "fieldType": "string",
            "operator": "=",
            "criteriaOperator": "AND"
          }
        ]
      },
      {
        "value": "HVUCIA-dismantled",
        "criteria": [
          {
            "field": "properties.objectFormStatusIdPrefix",
            "value": "84",
            "fieldType": "number",
            "operator": "=",
            "criteriaOperator": "AND"
          }
        ]
      },
      {
        "value": "HVUCIA-outOfService",
        "criteria": [
          {
            "field": "properties.objectFormStatusIdPrefix",
            "value": "86",
            "fieldType": "number",
            "operator": "=",
            "criteriaOperator": "AND"
          }
        ]
      },
      {
        "value": "HVUCIA",
        "criteria": []
      }
    ],
    "sizeRules": [],
    "labelRules": [],
    "tooltipRules": [
      {
        "value": "'<strong>'+context.feature.properties.pucId+' '+translate.instant(context.feature.properties.objectCode)+'</strong><p class=\"tooltip-line\">'+context.feature.properties.code+'</p><p class=\"tooltip-line\"> '+translate.instant(context.feature.properties.status)+'</p><p class=\"tooltip-line\"> '+translate.instant('HV Grid')+'</p>'",
        "criteria": []
      }
    ],
    "menuHeaderDataRules": []
  },
  {
    "classIds": "HVUCIU",
    "styles": [
      {
        "styleId": "TEMPLATE",
        "styleType": "LINE",
        "description": "HVUCIU_TEMPLATE",
        "defaultStyle": false,
        "attributes": [
          { "name": "classTemplate", "value": "true" }
        ],
        "iconUrl": "assets/app/img/map-markers/puc/LINE/line.svg",
        "color": "#FF0000",
        "weight": 2,
        "dashArray": "6,3"
      },
      {
        "styleId": "SEARCH_TEMPLATE",
        "styleType": "LINE",
        "description": "SEARCH_TEMPLATE",
        "defaultStyle": false,
        "attributes": [
          { "name": "searchClassTemplate", "value": "true" }
        ],
        "iconUrl": "assets/app/img/map-markers/puc/LINE/line.svg",
        "color": "#FFFFFF",
        "weight": 2,
        "dashArray": "6,3"
      },
      {
        "styleId": "HVUCIU",
        "styleType": "LINE",
        "description": "HVUCIU",
        "defaultStyle": false,
        "attributes": [],
        "color": "#ff0000",
        "iconUrl": "assets/app/img/map-markers/puc/LINE/line.svg",
        "weight": 2,
        "dashArray": "6,3"
      },
      {
        "styleId": "HVUCIU-editMode",
        "styleType": "LINE",
        "description": "HVUCIU-editMode",
        "defaultStyle": false,
        "attributes": [],
        "color": "#999999",
        "iconUrl": "assets/app/img/map-markers/puc/LINE/line.svg",
        "weight": 2,
        "dashArray": "6,3"
      },
      {
        "styleId": "HVUCIU-dismantled",
        "styleType": "LINE",
        "description": "HVUCIU-dismantled",
        "defaultStyle": false,
        "attributes": [],
        "color": "yellow",
        "iconUrl": "assets/app/img/map-markers/puc/LINE/line.svg",
        "weight": 2,
        "dashArray": "6,3"
      },
      {
        "styleId": "HVUCIU-outOfService",
        "styleType": "LINE",
        "description": "HVUCIU-outOfService",
        "defaultStyle": false,
        "attributes": [],
        "color": "violet",
        "iconUrl": "assets/app/img/map-markers/puc/LINE/line.svg",
        "weight": 2,
        "dashArray": "6,3"
      }
    ],
    "styleRules": [
      {
        "value": "HVUCIU-editMode",
        "criteria": [
          {
            "field": "properties.editMode",
            "value": "true",
            "fieldType": "string",
            "operator": "=",
            "criteriaOperator": "AND"
          }
        ]
      },
      {
        "value": "HVUCIU-dismantled",
        "criteria": [
          {
            "field": "properties.objectFormStatusIdPrefix",
            "value": "84",
            "fieldType": "number",
            "operator": "=",
            "criteriaOperator": "AND"
          }
        ]
      },
      {
        "value": "HVUCIU-outOfService",
        "criteria": [
          {
            "field": "properties.objectFormStatusIdPrefix",
            "value": "86",
            "fieldType": "number",
            "operator": "=",
            "criteriaOperator": "AND"
          }
        ]
      },
      {
        "value": "HVUCIU",
        "criteria": []
      }
    ],
    "sizeRules": [],
    "labelRules": [],
    "tooltipRules": [
      {
        "value": "'<strong>'+context.feature.properties.pucId+' '+translate.instant(context.feature.properties.objectCode)+'</strong><p class=\"tooltip-line\">'+context.feature.properties.code+'</p><p class=\"tooltip-line\"> '+translate.instant(context.feature.properties.status)+'</p><p class=\"tooltip-line\"> '+translate.instant('HV Grid')+'</p>'",
        "criteria": []
      }
    ],
    "menuHeaderDataRules": []
  },
  {
    "classIds": "HVUCIG",
    "styles": [
      {
        "styleId": "TEMPLATE",
        "styleType": "LINE",
        "description": "HVUCIG_TEMPLATE",
        "defaultStyle": false,
        "attributes": [
          { "name": "classTemplate", "value": "true" }
        ],
        "iconUrl": "assets/app/img/map-markers/puc/LINE/line.svg",
        "color": "#FF0000",
        "weight": 4,
        "dashArray": "10,2"
      },
      {
        "styleId": "SEARCH_TEMPLATE",
        "styleType": "LINE",
        "description": "SEARCH_TEMPLATE",
        "defaultStyle": false,
        "attributes": [
          { "name": "searchClassTemplate", "value": "true" }
        ],
        "iconUrl": "assets/app/img/map-markers/puc/LINE/line.svg",
        "color": "#FFFFFF",
        "weight": 4,
        "dashArray": "10,2"
      },
      {
        "styleId": "HVUCIG",
        "styleType": "LINE",
        "description": "HVUCIG",
        "defaultStyle": false,
        "attributes": [],
        "color": "#ff0000",
        "iconUrl": "assets/app/img/map-markers/puc/LINE/line.svg",
        "weight": 4,
        "dashArray": "10,2"
      },
      {
        "styleId": "HVUCIG-editMode",
        "styleType": "LINE",
        "description": "HVUCIG-editMode",
        "defaultStyle": false,
        "attributes": [],
        "color": "#999999",
        "iconUrl": "assets/app/img/map-markers/puc/LINE/line.svg",
        "weight": 4,
        "dashArray": "10,2"
      },
      {
        "styleId": "HVUCIG-dismantled",
        "styleType": "LINE",
        "description": "HVUCIG-dismantled",
        "defaultStyle": false,
        "attributes": [],
        "color": "yellow",
        "iconUrl": "assets/app/img/map-markers/puc/LINE/line.svg",
        "weight": 4,
        "dashArray": "10,2"
      },
      {
        "styleId": "HVUCIG-outOfService",
        "styleType": "LINE",
        "description": "HVUCIG-outOfService",
        "defaultStyle": false,
        "attributes": [],
        "color": "violet",
        "iconUrl": "assets/app/img/map-markers/puc/LINE/line.svg",
        "weight": 4,
        "dashArray": "10,2"
      }
    ],
    "styleRules": [
      {
        "value": "HVUCIG-editMode",
        "criteria": [
          {
            "field": "properties.editMode",
            "value": "true",
            "fieldType": "string",
            "operator": "=",
            "criteriaOperator": "AND"
          }
        ]
      },
      {
        "value": "HVUCIG-dismantled",
        "criteria": [
          {
            "field": "properties.objectFormStatusIdPrefix",
            "value": "84",
            "fieldType": "number",
            "operator": "=",
            "criteriaOperator": "AND"
          }
        ]
      },
      {
        "value": "HVUCIG-outOfService",
        "criteria": [
          {
            "field": "properties.objectFormStatusIdPrefix",
            "value": "86",
            "fieldType": "number",
            "operator": "=",
            "criteriaOperator": "AND"
          }
        ]
      },
      {
        "value": "HVUCIG",
        "criteria": []
      }
    ],
    "sizeRules": [],
    "labelRules": [],
    "tooltipRules": [
      {
        "value": "'<strong>'+context.feature.properties.pucId+' '+translate.instant(context.feature.properties.objectCode)+'</strong><p class=\"tooltip-line\">'+context.feature.properties.code+'</p><p class=\"tooltip-line\"> '+translate.instant(context.feature.properties.status)+'</p><p class=\"tooltip-line\"> '+translate.instant('HV Grid')+'</p>'",
        "criteria": []
      }
    ],
    "menuHeaderDataRules": []
  },
  {
    "classIds": "HLVUCI",
    "styles": [
      {
        "styleId": "TEMPLATE",
        "styleType": "LINE",
        "description": "HLVUCI_TEMPLATE",
        "defaultStyle": false,
        "attributes": [
          { "name": "classTemplate", "value": "true" }
        ],
        "iconUrl": "assets/app/img/map-markers/puc/LINE/line.svg",
        "color": "#FF0000",
        "weight": 4,
        "dashArray": null
      },
      {
        "styleId": "SEARCH_TEMPLATE",
        "styleType": "LINE",
        "description": "SEARCH_TEMPLATE",
        "defaultStyle": false,
        "attributes": [
          { "name": "searchClassTemplate", "value": "true" }
        ],
        "iconUrl": "assets/app/img/map-markers/puc/LINE/line.svg",
        "color": "#FFFFFF",
        "weight": 4,
        "dashArray": null
      },
      {
        "styleId": "HLVUCI",
        "styleType": "LINE",
        "description": "HLVUCI",
        "defaultStyle": false,
        "attributes": [],
        "color": "#ff0000",
        "iconUrl": "assets/app/img/map-markers/puc/LINE/line.svg",
        "weight": 4,
        "dashArray": null
      },
      {
        "styleId": "HLVUCI-editMode",
        "styleType": "LINE",
        "description": "HLVUCI-editMode",
        "defaultStyle": false,
        "attributes": [],
        "color": "#999999",
        "iconUrl": "assets/app/img/map-markers/puc/LINE/line.svg",
        "weight": 4,
        "dashArray": null
      },
      {
        "styleId": "HLVUCI-dismantled",
        "styleType": "LINE",
        "description": "HLVUCI-dismantled",
        "defaultStyle": false,
        "attributes": [],
        "color": "yellow",
        "iconUrl": "assets/app/img/map-markers/puc/LINE/line.svg",
        "weight": 4,
        "dashArray": null
      },
      {
        "styleId": "HLVUCI-outOfService",
        "styleType": "LINE",
        "description": "HLVUCI-outOfService",
        "defaultStyle": false,
        "attributes": [],
        "color": "violet",
        "iconUrl": "assets/app/img/map-markers/puc/LINE/line.svg",
        "weight": 4,
        "dashArray": null
      }
    ],
    "styleRules": [
      {
        "value": "HLVUCI-editMode",
        "criteria": [
          {
            "field": "properties.editMode",
            "value": "true",
            "fieldType": "string",
            "operator": "=",
            "criteriaOperator": "AND"
          }
        ]
      },
      {
        "value": "HLVUCI-dismantled",
        "criteria": [
          {
            "field": "properties.objectFormStatusIdPrefix",
            "value": "84",
            "fieldType": "number",
            "operator": "=",
            "criteriaOperator": "AND"
          }
        ]
      },
      {
        "value": "HLVUCI-outOfService",
        "criteria": [
          {
            "field": "properties.objectFormStatusIdPrefix",
            "value": "86",
            "fieldType": "number",
            "operator": "=",
            "criteriaOperator": "AND"
          }
        ]
      },
      {
        "value": "HLVUCI",
        "criteria": []
      }
    ],
    "sizeRules": [],
    "labelRules": [],
    "tooltipRules": [
      {
        "value": "'<strong>'+context.feature.properties.pucId+' '+translate.instant(context.feature.properties.objectCode)+'</strong><p class=\"tooltip-line\">'+context.feature.properties.code+'</p><p class=\"tooltip-line\"> '+translate.instant(context.feature.properties.status)+'</p><p class=\"tooltip-line\"> '+translate.instant('HV Grid')+'</p>'",
        "criteria": []
      }
    ],
    "menuHeaderDataRules": []
  }
]

<> 2025-06-10T144110.200.json
<> 2025-06-10T135856.200.json

###