POST http://192.168.1.2:8080/definitions/import?layerGroup=COMPOSER&tags=composer,hv
Content-Type: application/json

[
  {
    "classIds": "HVCACN",
    "styles": [
      {
        "styleId": "TEMPLATE",
        "styleType": "POINT",
        "description": "HVCACN_TEMPLATE",
        "defaultStyle": false,
        "attributes": [
          { "name": "classTemplate", "value": "true" }
        ],
        "iconUrl": "assets/app/img/map-markers/puc/CL_MONTANTI_MT/square-fe.svg",
        "weight": 2,
        "color": "#FF0000"
      },
      {
        "styleId": "SEARCH_TEMPLATE",
        "styleType": "POINT",
        "description": "SEARCH_TEMPLATE",
        "defaultStyle": false,
        "attributes": [
          { "name": "searchClassTemplate", "value": "true" }
        ],
        "iconUrl": "assets/app/img/map-markers/puc/CL_MONTANTI_MT/square-fe.svg",
        "weight": 2,
        "color": "#FFFFFF"
      },
      {
        "styleId": "HVCACN",
        "styleType": "POINT",
        "description": "HVCACN",
        "defaultStyle": false,
        "attributes": [],
        "color": "#ff0000",
        "iconUrl": "assets/app/img/map-markers/puc/CL_MONTANTI_MT/square-fe.svg",
        "weight": 2
      },
      {
        "styleId": "HVCACN-dismantled",
        "styleType": "POINT",
        "description": "HVCACN",
        "defaultStyle": false,
        "attributes": [],
        "color": "yellow",
        "iconUrl": "assets/app/img/map-markers/puc/CL_MONTANTI_MT/square-fe.svg",
        "weight": 2
      },
      {
        "styleId": "HVCACN-outOfService",
        "styleType": "POINT",
        "description": "HVCACN",
        "defaultStyle": false,
        "attributes": [],
        "color": "violet",
        "iconUrl": "assets/app/img/map-markers/puc/CL_MONTANTI_MT/square-fe.svg",
        "weight": 2
      },
      {
        "styleId": "HVCACN-editMode",
        "styleType": "POINT",
        "description": "HVCACN-editMode",
        "defaultStyle": false,
        "attributes": [],
        "color": "#999999",
        "iconUrl": "assets/app/img/map-markers/puc/CL_MONTANTI_MT/square-fe.svg",
        "weight": 2
      }
    ],
    "styleRules": [
      {
        "value": "HVCACN-editMode",
        "criteria": [
          {
            "field": "properties.editMode",
            "value": "true",
            "fieldType": "string",
            "operator": "=",
            "criteriaOperator": "AND"
          }
        ]
      },
      {
        "value": "HVCACN-dismantled",
        "criteria": [
          {
            "field": "properties.objectFormStatusIdPrefix",
            "value": "39",
            "fieldType": "number",
            "operator": "=",
            "criteriaOperator": "AND"
          }
        ]
      },
      {
        "value": "HVCACN-outOfService",
        "criteria": [
          {
            "field": "properties.objectFormStatusIdPrefix",
            "value": "41",
            "fieldType": "number",
            "operator": "=",
            "criteriaOperator": "AND"
          }
        ]
      },
      {
        "value": "HVCACN",
        "criteria": []
      }
    ],
    "sizeRules": [
      {
        "value": "24",
        "criteria": []
      }
    ],
    "labelRules": [],
    "tooltipRules": [
      {
        "value": "'<strong>'+context.feature.properties.pucId+' '+translate.instant(context.feature.properties.objectCode)+'</strong><p class=\"tooltip-line\">'+context.feature.properties.code+'</p><p class=\"tooltip-line\"> '+translate.instant(context.feature.properties.status)+'</p><p class=\"tooltip-line\"> '+translate.instant('HV Grid')+'</p>'",
        "criteria": []
      }
    ],
    "menuHeaderDataRules": []
  },
  {
    "classIds": "HVPS01",
    "styles": [
      {
        "styleId": "TEMPLATE",
        "styleType": "POINT",
        "description": "HVPS01_TEMPLATE",
        "defaultStyle": false,
        "attributes": [
          { "name": "classTemplate", "value": "true" }
        ],
        "iconUrl": "assets/app/img/map-markers/puc/CL_AT_NODE/cabina-primaria.svg",
        "color": "#FF0000"
      },
      {
        "styleId": "SEARCH_TEMPLATE",
        "styleType": "POINT",
        "description": "SEARCH_TEMPLATE",
        "defaultStyle": false,
        "attributes": [
          { "name": "searchClassTemplate", "value": "true" }
        ],
        "iconUrl": "assets/app/img/map-markers/puc/CL_AT_NODE/cabina-primaria.svg",
        "color": "#FFFFFF"
      },
      {
        "styleId": "HVPS01",
        "styleType": "POINT",
        "description": "HVPS01",
        "defaultStyle": false,
        "attributes": [],
        "color": "#ff0000",
        "iconUrl": "assets/app/img/map-markers/puc/CL_AT_NODE/cabina-primaria.svg"
      },
      {
        "styleId": "HVPS01-dismantled",
        "styleType": "POINT",
        "description": "HVPS01",
        "defaultStyle": false,
        "attributes": [],
        "color": "yellow",
        "iconUrl": "assets/app/img/map-markers/puc/CL_AT_NODE/cabina-primaria.svg"
      },
      {
        "styleId": "HVPS01-outOfService",
        "styleType": "POINT",
        "description": "HVPS01",
        "defaultStyle": false,
        "attributes": [],
        "color": "violet",
        "iconUrl": "assets/app/img/map-markers/puc/CL_AT_NODE/cabina-primaria.svg"
      },
      {
        "styleId": "HVPS01-editMode",
        "styleType": "POINT",
        "description": "HVPS01-editMode",
        "defaultStyle": false,
        "attributes": [],
        "color": "#999999",
        "iconUrl": "assets/app/img/map-markers/puc/CL_AT_NODE/cabina-primaria.svg"
      }
    ],
    "styleRules": [
      {
        "value": "HVPS01-editMode",
        "criteria": [
          {
            "field": "properties.editMode",
            "value": "true",
            "fieldType": "string",
            "operator": "=",
            "criteriaOperator": "AND"
          }
        ]
      },
      {
        "value": "HVPS01-dismantled",
        "criteria": [
          {
            "field": "properties.objectFormStatusIdPrefix",
            "value": "39",
            "fieldType": "number",
            "operator": "=",
            "criteriaOperator": "AND"
          }
        ]
      },
      {
        "value": "HVPS01-outOfService",
        "criteria": [
          {
            "field": "properties.objectFormStatusIdPrefix",
            "value": "41",
            "fieldType": "number",
            "operator": "=",
            "criteriaOperator": "AND"
          }
        ]
      },
      {
        "value": "HVPS01",
        "criteria": []
      }
    ],
    "sizeRules": [
      {
        "value": "24",
        "criteria": []
      }
    ],
    "labelRules": [],
    "tooltipRules": [
      {
        "value": "'<strong>'+context.feature.properties.pucId+' '+translate.instant(context.feature.properties.objectCode)+'</strong><p class=\"tooltip-line\">'+context.feature.properties.code+'</p><p class=\"tooltip-line\"> '+translate.instant(context.feature.properties.status)+'</p><p class=\"tooltip-line\"> '+translate.instant('HV Grid')+'</p>'",
        "criteria": []
      }
    ],
    "menuHeaderDataRules": []
  },
  {
    "classIds": "HVPS04",
    "styles": [
      {
        "styleId": "TEMPLATE",
        "styleType": "POINT",
        "description": "HVPS04_TEMPLATE",
        "defaultStyle": false,
        "attributes": [
          { "name": "classTemplate", "value": "true" }
        ],
        "iconUrl": "assets/app/img/map-markers/puc/CL_AT_NODE/cabina-primaria.svg",
        "color": "#FF0000"
      },
      {
        "styleId": "SEARCH_TEMPLATE",
        "styleType": "POINT",
        "description": "HVPS04_TEMPLATE",
        "defaultStyle": false,
        "attributes": [
          { "name": "searchClassTemplate", "value": "true" }
        ],
        "iconUrl": "assets/app/img/map-markers/puc/CL_AT_NODE/cabina-primaria.svg",
        "color": "#FFFFFF"
      },
      {
        "styleId": "HVPS04",
        "styleType": "POINT",
        "description": "HVPS04",
        "defaultStyle": false,
        "attributes": [],
        "color": "#ff0000",
        "iconUrl": "assets/app/img/map-markers/puc/CL_AT_NODE/cabina-primaria.svg"
      },
      {
        "styleId": "HVPS04-dismantled",
        "styleType": "POINT",
        "description": "HVPS04",
        "defaultStyle": false,
        "attributes": [],
        "color": "yellow",
        "iconUrl": "assets/app/img/map-markers/puc/CL_AT_NODE/cabina-primaria.svg"
      },
      {
        "styleId": "HVPS04-outOfService",
        "styleType": "POINT",
        "description": "HVPS04",
        "defaultStyle": false,
        "attributes": [],
        "color": "violet",
        "iconUrl": "assets/app/img/map-markers/puc/CL_AT_NODE/cabina-primaria.svg"
      },
      {
        "styleId": "HVPS04-editMode",
        "styleType": "POINT",
        "description": "HVPS04-editMode",
        "defaultStyle": false,
        "attributes": [],
        "color": "#999999",
        "iconUrl": "assets/app/img/map-markers/puc/CL_AT_NODE/cabina-primaria.svg"
      }
    ],
    "styleRules": [
      {
        "value": "HVPS04-editMode",
        "criteria": [
          {
            "field": "properties.editMode",
            "value": "true",
            "fieldType": "string",
            "operator": "=",
            "criteriaOperator": "AND"
          }
        ]
      },
      {
        "value": "HVPS04-dismantled",
        "criteria": [
          {
            "field": "properties.objectFormStatusIdPrefix",
            "value": "39",
            "fieldType": "number",
            "operator": "=",
            "criteriaOperator": "AND"
          }
        ]
      },
      {
        "value": "HVPS04-outOfService",
        "criteria": [
          {
            "field": "properties.objectFormStatusIdPrefix",
            "value": "41",
            "fieldType": "number",
            "operator": "=",
            "criteriaOperator": "AND"
          }
        ]
      },
      {
        "value": "HVPS04",
        "criteria": []
      }
    ],
    "sizeRules": [
      {
        "value": "24",
        "criteria": []
      }
    ],
    "labelRules": [],
    "tooltipRules": [
      {
        "value": "'<strong>'+context.feature.properties.pucId+' '+translate.instant(context.feature.properties.objectCode)+'</strong><p class=\"tooltip-line\">'+context.feature.properties.code+'</p><p class=\"tooltip-line\"> '+translate.instant(context.feature.properties.status)+'</p><p class=\"tooltip-line\"> '+translate.instant('HV Grid')+'</p>'",
        "criteria": []
      }
    ],
    "menuHeaderDataRules": []
  },
  {
    "classIds": "HVANSW",
    "styles": [
      {
        "styleId": "TEMPLATE",
        "styleType": "POINT",
        "description": "HVANSW_TEMPLATE",
        "defaultStyle": false,
        "attributes": [
          { "name": "classTemplate", "value": "true" }
        ],
        "iconUrl": "assets/app/img/map-markers/puc/CL_MT_NODE_3_4/sezionatore-mt-blk-fill_S.svg",
        "color": "#FF0000"
      },
      {
        "styleId": "SEARCH_TEMPLATE",
        "styleType": "POINT",
        "description": "SEARCH_TEMPLATE",
        "defaultStyle": false,
        "attributes": [
          { "name": "searchClassTemplate", "value": "true" }
        ],
        "iconUrl": "assets/app/img/map-markers/puc/CL_MT_NODE_3_4/sezionatore-mt-blk-fill_S.svg",
        "color": "#FFFFFF"
      },
      {
        "styleId": "HVANSW",
        "styleType": "POINT",
        "description": "HVANSW",
        "defaultStyle": false,
        "attributes": [],
        "color": "#ff0000",
        "iconUrl": "assets/app/img/map-markers/puc/CL_MT_NODE_3_4/sezionatore-mt-blk-fill_S.svg"
      },
      {
        "styleId": "HVANSW-dismantled",
        "styleType": "POINT",
        "description": "HVANSW",
        "defaultStyle": false,
        "attributes": [],
        "color": "yellow",
        "iconUrl": "assets/app/img/map-markers/puc/CL_MT_NODE_3_4/sezionatore-mt-blk-fill_S.svg"
      },
      {
        "styleId": "HVANSW-outOfService",
        "styleType": "POINT",
        "description": "HVANSW",
        "defaultStyle": false,
        "attributes": [],
        "color": "violet",
        "iconUrl": "assets/app/img/map-markers/puc/CL_MT_NODE_3_4/sezionatore-mt-blk-fill_S.svg"
      },
      {
        "styleId": "HVANSW-editMode",
        "styleType": "POINT",
        "description": "HVANSW-editMode",
        "defaultStyle": false,
        "attributes": [],
        "color": "#999999",
        "iconUrl": "assets/app/img/map-markers/puc/CL_MT_NODE_3_4/sezionatore-mt-blk-fill_S.svg"
      }
    ],
    "styleRules": [
      {
        "value": "HVANSW-editMode",
        "criteria": [
          {
            "field": "properties.editMode",
            "value": "true",
            "fieldType": "string",
            "operator": "=",
            "criteriaOperator": "AND"
          }
        ]
      },
      {
        "value": "HVANSW-dismantled",
        "criteria": [
          {
            "field": "properties.objectFormStatusIdPrefix",
            "value": "39",
            "fieldType": "number",
            "operator": "=",
            "criteriaOperator": "AND"
          }
        ]
      },
      {
        "value": "HVANSW-outOfService",
        "criteria": [
          {
            "field": "properties.objectFormStatusIdPrefix",
            "value": "41",
            "fieldType": "number",
            "operator": "=",
            "criteriaOperator": "AND"
          }
        ]
      },
      {
        "value": "HVANSW",
        "criteria": []
      }
    ],
    "sizeRules": [
      {
        "value": "24",
        "criteria": []
      }
    ],
    "labelRules": [],
    "tooltipRules": [
      {
        "value": "'<strong>'+context.feature.properties.pucId+' '+translate.instant(context.feature.properties.objectCode)+'</strong><p class=\"tooltip-line\">'+context.feature.properties.code+'</p><p class=\"tooltip-line\"> '+translate.instant(context.feature.properties.status)+'</p><p class=\"tooltip-line\"> '+translate.instant('HV Grid')+'</p>'",
        "criteria": []
      }
    ],
    "menuHeaderDataRules": []
  },
  {
    "classIds": "HVANIN",
    "styles": [
      {
        "styleId": "TEMPLATE",
        "styleType": "POINT",
        "description": "HVANIN_TEMPLATE",
        "defaultStyle": false,
        "attributes": [
          { "name": "classTemplate", "value": "true" }
        ],
        "iconUrl": "assets/app/img/map-markers/puc/CL_MT_NODE_3_4/Interruttore.svg",
        "weight": 5,
        "color": "#FF0000"
      },
      {
        "styleId": "SEARCH_TEMPLATE",
        "styleType": "POINT",
        "description": "SEARCH_TEMPLATE",
        "defaultStyle": false,
        "attributes": [
          { "name": "searchClassTemplate", "value": "true" }
        ],
        "iconUrl": "assets/app/img/map-markers/puc/CL_MT_NODE_3_4/Interruttore.svg",
        "weight": 5,
        "color": "#FFFFFF"
      },
      {
        "styleId": "HVANIN",
        "styleType": "POINT",
        "description": "HVANIN",
        "defaultStyle": false,
        "attributes": [],
        "color": "#ff0000",
        "iconUrl": "assets/app/img/map-markers/puc/CL_MT_NODE_3_4/Interruttore.svg",
        "weight": 5
      },
      {
        "styleId": "HVANIN-dismantled",
        "styleType": "POINT",
        "description": "HVANIN",
        "defaultStyle": false,
        "attributes": [],
        "color": "yellow",
        "iconUrl": "assets/app/img/map-markers/puc/CL_MT_NODE_3_4/Interruttore.svg",
        "weight": 5
      },
      {
        "styleId": "HVANIN-outOfService",
        "styleType": "POINT",
        "description": "HVANIN",
        "defaultStyle": false,
        "attributes": [],
        "color": "violet",
        "iconUrl": "assets/app/img/map-markers/puc/CL_MT_NODE_3_4/Interruttore.svg",
        "weight": 5
      },
      {
        "styleId": "HVANIN-editMode",
        "styleType": "POINT",
        "description": "HVANIN-editMode",
        "defaultStyle": false,
        "attributes": [],
        "color": "#999999",
        "iconUrl": "assets/app/img/map-markers/puc/CL_MT_NODE_3_4/Interruttore.svg",
        "weight": 5
      }
    ],
    "styleRules": [
      {
        "value": "HVANIN-editMode",
        "criteria": [
          {
            "field": "properties.editMode",
            "value": "true",
            "fieldType": "string",
            "operator": "=",
            "criteriaOperator": "AND"
          }
        ]
      },
      {
        "value": "HVANIN-dismantled",
        "criteria": [
          {
            "field": "properties.objectFormStatusIdPrefix",
            "value": "39",
            "fieldType": "number",
            "operator": "=",
            "criteriaOperator": "AND"
          }
        ]
      },
      {
        "value": "HVANIN-outOfService",
        "criteria": [
          {
            "field": "properties.objectFormStatusIdPrefix",
            "value": "41",
            "fieldType": "number",
            "operator": "=",
            "criteriaOperator": "AND"
          }
        ]
      },
      {
        "value": "HVANIN",
        "criteria": []
      }
    ],
    "sizeRules": [
      {
        "value": "24",
        "criteria": []
      }
    ],
    "labelRules": [],
    "tooltipRules": [
      {
        "value": "'<strong>'+context.feature.properties.pucId+' '+translate.instant(context.feature.properties.objectCode)+'</strong><p class=\"tooltip-line\">'+context.feature.properties.code+'</p><p class=\"tooltip-line\"> '+translate.instant(context.feature.properties.status)+'</p><p class=\"tooltip-line\"> '+translate.instant('HV Grid')+'</p>'",
        "criteria": []
      }
    ],
    "menuHeaderDataRules": []
  },
  {
    "classIds": "HVNTNO",
    "styles": [
      {
        "styleId": "TEMPLATE",
        "styleType": "POINT",
        "description": "HVNTNO_TEMPLATE",
        "defaultStyle": false,
        "attributes": [
          { "name": "classTemplate", "value": "true" }
        ],
        "iconUrl": "assets/app/img/map-markers/puc/CL_MT_NODE_3_4/nodo-rigido-MT.svg",
        "color": "#FF0000"
      },
      {
        "styleId": "SEARCH_TEMPLATE",
        "styleType": "POINT",
        "description": "SEARCH_TEMPLATE",
        "defaultStyle": false,
        "attributes": [
          { "name": "searchClassTemplate", "value": "true" }
        ],
        "iconUrl": "assets/app/img/map-markers/puc/CL_MT_NODE_3_4/nodo-rigido-MT.svg",
        "color": "#FFFFFF"
      },
      {
        "styleId": "HVNTNO",
        "styleType": "POINT",
        "description": "HVNTNO",
        "defaultStyle": false,
        "attributes": [],
        "color": "#ff0000",
        "iconUrl": "assets/app/img/map-markers/puc/CL_MT_NODE_3_4/nodo-rigido-MT.svg"
      },
      {
        "styleId": "HVNTNO-dismantled",
        "styleType": "POINT",
        "description": "HVNTNO",
        "defaultStyle": false,
        "attributes": [],
        "color": "yellow",
        "iconUrl": "assets/app/img/map-markers/puc/CL_MT_NODE_3_4/nodo-rigido-MT.svg"
      },
      {
        "styleId": "HVNTNO-outOfService",
        "styleType": "POINT",
        "description": "HVNTNO",
        "defaultStyle": false,
        "attributes": [],
        "color": "violet",
        "iconUrl": "assets/app/img/map-markers/puc/CL_MT_NODE_3_4/nodo-rigido-MT.svg"
      },
      {
        "styleId": "HVNTNO-editMode",
        "styleType": "POINT",
        "description": "HVNTNO-editMode",
        "defaultStyle": false,
        "attributes": [],
        "color": "#999999",
        "iconUrl": "assets/app/img/map-markers/puc/CL_MT_NODE_3_4/nodo-rigido-MT.svg"
      }
    ],
    "styleRules": [
      {
        "value": "HVNTNO-editMode",
        "criteria": [
          {
            "field": "properties.editMode",
            "value": "true",
            "fieldType": "string",
            "operator": "=",
            "criteriaOperator": "AND"
          }
        ]
      },
      {
        "value": "HVNTNO-dismantled",
        "criteria": [
          {
            "field": "properties.objectFormStatusIdPrefix",
            "value": "39",
            "fieldType": "number",
            "operator": "=",
            "criteriaOperator": "AND"
          }
        ]
      },
      {
        "value": "HVNTNO-outOfService",
        "criteria": [
          {
            "field": "properties.objectFormStatusIdPrefix",
            "value": "41",
            "fieldType": "number",
            "operator": "=",
            "criteriaOperator": "AND"
          }
        ]
      },
      {
        "value": "HVNTNO",
        "criteria": []
      }
    ],
    "sizeRules": [
      {
        "value": "24",
        "criteria": []
      }
    ],
    "labelRules": [],
    "tooltipRules": [
      {
        "value": "'<strong>'+context.feature.properties.pucId+' '+translate.instant(context.feature.properties.objectCode)+'</strong><p class=\"tooltip-line\">'+context.feature.properties.code+'</p><p class=\"tooltip-line\"> '+translate.instant(context.feature.properties.status)+'</p><p class=\"tooltip-line\"> '+translate.instant('HV Grid')+'</p>'",
        "criteria": []
      }
    ],
    "menuHeaderDataRules": []
  },
  {
    "classIds": "HVNTJC",
    "styles": [
      {
        "styleId": "TEMPLATE",
        "styleType": "POINT",
        "description": "HVNTJC_TEMPLATE",
        "defaultStyle": false,
        "attributes": [
          {"name": "classTemplate", "value": "true" }
        ],
        "iconUrl": "assets/app/img/map-markers/puc/CL_BT_NODE_G/nodo-G.svg",
        "color": "#FF0000"
      },
      {
        "styleId": "SEARCH_TEMPLATE",
        "styleType": "POINT",
        "description": "SEARCH_TEMPLATE",
        "defaultStyle": false,
        "attributes": [
          {"name": "searchClassTemplate", "value": "true" }
        ],
        "iconUrl": "assets/app/img/map-markers/puc/CL_BT_NODE_G/nodo-G.svg",
        "color": "#FFFFFF"
      },
      {
        "styleId": "HVNTJC",
        "styleType": "POINT",
        "description": "HVNTJC",
        "defaultStyle": false,
        "attributes": [],
        "color": "#ff0000",
        "iconUrl": "assets/app/img/map-markers/puc/CL_BT_NODE_G/nodo-G.svg"
      },
      {
        "styleId": "HVNTJC-dismantled",
        "styleType": "POINT",
        "description": "HVNTJC",
        "defaultStyle": false,
        "attributes": [],
        "color": "yellow",
        "iconUrl": "assets/app/img/map-markers/puc/CL_BT_NODE_G/nodo-G.svg"
      },
      {
        "styleId": "HVNTJC-outOfService",
        "styleType": "POINT",
        "description": "HVNTJC",
        "defaultStyle": false,
        "attributes": [],
        "color": "violet",
        "iconUrl": "assets/app/img/map-markers/puc/CL_BT_NODE_G/nodo-G.svg"
      },
      {
        "styleId": "HVNTJC-editMode",
        "styleType": "POINT",
        "description": "HVNTJC-editMode",
        "defaultStyle": false,
        "attributes": [],
        "color": "#999999",
        "iconUrl": "assets/app/img/map-markers/puc/CL_BT_NODE_G/nodo-G.svg"
      }
    ],
    "styleRules": [
      {
        "value": "HVNTJC-editMode",
        "criteria": [
          {
            "field": "properties.editMode",
            "value": "true",
            "fieldType": "string",
            "operator": "=",
            "criteriaOperator": "AND"
          }
        ]
      },
      {
        "value": "HVNTJC-dismantled",
        "criteria": [
          {
            "field": "properties.objectFormStatusIdPrefix",
            "value": "39",
            "fieldType": "number",
            "operator": "=",
            "criteriaOperator": "AND"
          }
        ]
      },
      {
        "value": "HVNTJC-outOfService",
        "criteria": [
          {
            "field": "properties.objectFormStatusIdPrefix",
            "value": "41",
            "fieldType": "number",
            "operator": "=",
            "criteriaOperator": "AND"
          }
        ]
      },
      {
        "value": "HVNTJC",
        "criteria": []
      }
    ],
    "sizeRules": [
      {
        "value": "24",
        "criteria": []
      }
    ],
    "labelRules": [],
    "tooltipRules": [
      {
        "value": "'<strong>'+context.feature.properties.pucId+' '+translate.instant(context.feature.properties.objectCode)+'</strong><p class=\"tooltip-line\">'+context.feature.properties.code+'</p><p class=\"tooltip-line\"> '+translate.instant(context.feature.properties.status)+'</p><p class=\"tooltip-line\"> '+translate.instant('HV Grid')+'</p>'",
        "criteria": []
      }
    ],
    "menuHeaderDataRules": []
  },
  {
    "classIds": "HVNTST",
    "styles": [
      {
        "styleId": "TEMPLATE",
        "styleType": "POINT",
        "description": "HVNTST_TEMPLATE",
        "defaultStyle": false,
        "attributes": [
          { "name": "classTemplate", "value": "true" }
        ],
        "iconUrl": "assets/app/img/map-markers/puc/CL_BT_NODE_G/circle.svg",
        "weight": 2,
        "color": "#FF0000"
      },
      {
        "styleId": "SEARCH_TEMPLATE",
        "styleType": "POINT",
        "description": "SEARCH_TEMPLATE",
        "defaultStyle": false,
        "attributes": [
          { "name": "searchClassTemplate", "value": "true" }
        ],
        "iconUrl": "assets/app/img/map-markers/puc/CL_BT_NODE_G/circle.svg",
        "weight": 2,
        "color": "#FFFFFF"
      },
      {
        "styleId": "HVNTST",
        "styleType": "POINT",
        "description": "HVNTST",
        "defaultStyle": false,
        "attributes": [],
        "color": "#ff0000",
        "iconUrl": "assets/app/img/map-markers/puc/CL_BT_NODE_G/circle.svg",
        "weight": 2
      },
      {
        "styleId": "HVNTST-dismantled",
        "styleType": "POINT",
        "description": "HVNTST",
        "defaultStyle": false,
        "attributes": [],
        "color": "yellow",
        "iconUrl": "assets/app/img/map-markers/puc/CL_BT_NODE_G/circle.svg",
        "weight": 2
      },
      {
        "styleId": "HVNTST-outOfService",
        "styleType": "POINT",
        "description": "HVNTST",
        "defaultStyle": false,
        "attributes": [],
        "color": "violet",
        "iconUrl": "assets/app/img/map-markers/puc/CL_BT_NODE_G/circle.svg",
        "weight": 2
      },
      {
        "styleId": "HVNTST-editMode",
        "styleType": "POINT",
        "description": "HVNTST-editMode",
        "defaultStyle": false,
        "attributes": [],
        "color": "#999999",
        "iconUrl": "assets/app/img/map-markers/puc/CL_BT_NODE_G/circle.svg",
        "weight": 2
      }
    ],
    "styleRules": [
      {
        "value": "HVNTST-editMode",
        "criteria": [
          {
            "field": "properties.editMode",
            "value": "true",
            "fieldType": "string",
            "operator": "=",
            "criteriaOperator": "AND"
          }
        ]
      },
      {
        "value": "HVNTST-dismantled",
        "criteria": [
          {
            "field": "properties.objectFormStatusIdPrefix",
            "value": "39",
            "fieldType": "number",
            "operator": "=",
            "criteriaOperator": "AND"
          }
        ]
      },
      {
        "value": "HVNTST-outOfService",
        "criteria": [
          {
            "field": "properties.objectFormStatusIdPrefix",
            "value": "41",
            "fieldType": "number",
            "operator": "=",
            "criteriaOperator": "AND"
          }
        ]
      },
      {
        "value": "HVNTST",
        "criteria": []
      }
    ],
    "sizeRules": [
      {
        "value": "10",
        "criteria": []
      }
    ],
    "labelRules": [],
    "tooltipRules": [
      {
        "value": "'<strong>'+context.feature.properties.pucId+' '+translate.instant(context.feature.properties.objectCode)+'</strong><p class=\"tooltip-line\">'+context.feature.properties.code+'</p><p class=\"tooltip-line\"> '+translate.instant(context.feature.properties.status)+'</p><p class=\"tooltip-line\"> '+translate.instant('HV Grid')+'</p>'",
        "criteria": []
      }
    ],
    "menuHeaderDataRules": []
  },
  {
    "classIds": "HVCLDP",
    "styles": [
      {
        "styleId": "TEMPLATE",
        "styleType": "POINT",
        "description": "HVCLDP_TEMPLATE",
        "defaultStyle": false,
        "attributes": [
          { "name": "classTemplate", "value": "true" }
        ],
        "iconUrl": "assets/app/img/map-markers/puc/CL_BT_NODE_7/nodo-consegna-passivo.svg",
        "color": "#FF0000"
      },
      {
        "styleId": "SEARCH_TEMPLATE",
        "styleType": "POINT",
        "description": "SEARCH_TEMPLATE",
        "defaultStyle": false,
        "attributes": [
          { "name": "searchClassTemplate", "value": "true" }
        ],
        "iconUrl": "assets/app/img/map-markers/puc/CL_BT_NODE_7/nodo-consegna-passivo.svg",
        "color": "#FFFFFF"
      },
      {
        "styleId": "HVCLDP",
        "styleType": "POINT",
        "description": "HVCLDP",
        "defaultStyle": false,
        "attributes": [],
        "color": "#ff0000",
        "iconUrl": "assets/app/img/map-markers/puc/CL_BT_NODE_7/nodo-consegna-passivo.svg"
      },
      {
        "styleId": "HVCLDP-dismantled",
        "styleType": "POINT",
        "description": "HVCLDP",
        "defaultStyle": false,
        "attributes": [],
        "color": "yellow",
        "iconUrl": "assets/app/img/map-markers/puc/CL_BT_NODE_7/nodo-consegna-passivo.svg"
      },
      {
        "styleId": "HVCLDP-outOfService",
        "styleType": "POINT",
        "description": "HVCLDP",
        "defaultStyle": false,
        "attributes": [],
        "color": "violet",
        "iconUrl": "assets/app/img/map-markers/puc/CL_BT_NODE_7/nodo-consegna-passivo.svg"
      },
      {
        "styleId": "HVCLDP-editMode",
        "styleType": "POINT",
        "description": "HVCLDP-editMode",
        "defaultStyle": false,
        "attributes": [],
        "color": "#999999",
        "iconUrl": "assets/app/img/map-markers/puc/CL_BT_NODE_7/nodo-consegna-passivo.svg"
      }
    ],
    "styleRules": [
      {
        "value": "HVCLDP-editMode",
        "criteria": [
          {
            "field": "properties.editMode",
            "value": "true",
            "fieldType": "string",
            "operator": "=",
            "criteriaOperator": "AND"
          }
        ]
      },
      {
        "value": "HVCLDP-dismantled",
        "criteria": [
          {
            "field": "properties.objectFormStatusIdPrefix",
            "value": "39",
            "fieldType": "number",
            "operator": "=",
            "criteriaOperator": "AND"
          }
        ]
      },
      {
        "value": "HVCLDP-outOfService",
        "criteria": [
          {
            "field": "properties.objectFormStatusIdPrefix",
            "value": "41",
            "fieldType": "number",
            "operator": "=",
            "criteriaOperator": "AND"
          }
        ]
      },
      {
        "value": "HVCLDP",
        "criteria": []
      }
    ],
    "sizeRules": [
      {
        "value": "24",
        "criteria": []
      }
    ],
    "labelRules": [],
    "tooltipRules": [
      {
        "value": "'<strong>'+context.feature.properties.pucId+' '+translate.instant(context.feature.properties.objectCode)+'</strong><p class=\"tooltip-line\">'+context.feature.properties.code+'</p><p class=\"tooltip-line\"> '+translate.instant(context.feature.properties.status)+'</p><p class=\"tooltip-line\"> '+translate.instant('HV Grid')+'</p>'",
        "criteria": []
      }
    ],
    "menuHeaderDataRules": []
  },
  {
    "classIds": "HVCDPC",
    "styles": [
      {
        "styleId": "TEMPLATE",
        "styleType": "POINT",
        "description": "HVCDPC_TEMPLATE",
        "defaultStyle": false,
        "attributes": [
          { "name": "classTemplate", "value": "true" }
        ],
        "iconUrl": "assets/app/img/map-markers/puc/CL_BT_NODE_7/nodo-consegna-BP606.svg",
        "color": "#FF0000"
      },
      {
        "styleId": "SEARCH_TEMPLATE",
        "styleType": "POINT",
        "description": "SEARCH_TEMPLATE",
        "defaultStyle": false,
        "attributes": [
          { "name": "searchClassTemplate", "value": "true" }
        ],
        "iconUrl": "assets/app/img/map-markers/puc/CL_BT_NODE_7/nodo-consegna-BP606.svg",
        "color": "#FFFFFF"
      },
      {
        "styleId": "HVCDPC",
        "styleType": "POINT",
        "description": "HVCDPC",
        "defaultStyle": false,
        "attributes": [],
        "color": "#ff0000",
        "iconUrl": "assets/app/img/map-markers/puc/CL_BT_NODE_7/nodo-consegna-BP606.svg"
      },
      {
        "styleId": "HVCDPC-dismantled",
        "styleType": "POINT",
        "description": "HVCDPC",
        "defaultStyle": false,
        "attributes": [],
        "color": "yellow",
        "iconUrl": "assets/app/img/map-markers/puc/CL_BT_NODE_7/nodo-consegna-BP606.svg"
      },
      {
        "styleId": "HVCDPC-outOfService",
        "styleType": "POINT",
        "description": "HVCDPC",
        "defaultStyle": false,
        "attributes": [],
        "color": "violet",
        "iconUrl": "assets/app/img/map-markers/puc/CL_BT_NODE_7/nodo-consegna-BP606.svg"
      },
      {
        "styleId": "HVCDPC-editMode",
        "styleType": "POINT",
        "description": "HVCDPC-editMode",
        "defaultStyle": false,
        "attributes": [],
        "color": "#999999",
        "iconUrl": "assets/app/img/map-markers/puc/CL_BT_NODE_7/nodo-consegna-BP606.svg"
      }
    ],
    "styleRules": [
      {
        "value": "HVCDPC-editMode",
        "criteria": [
          {
            "field": "properties.editMode",
            "value": "true",
            "fieldType": "string",
            "operator": "=",
            "criteriaOperator": "AND"
          }
        ]
      },
      {
        "value": "HVCDPC-dismantled",
        "criteria": [
          {
            "field": "properties.objectFormStatusIdPrefix",
            "value": "39",
            "fieldType": "number",
            "operator": "=",
            "criteriaOperator": "AND"
          }
        ]
      },
      {
        "value": "HVCDPC-outOfService",
        "criteria": [
          {
            "field": "properties.objectFormStatusIdPrefix",
            "value": "41",
            "fieldType": "number",
            "operator": "=",
            "criteriaOperator": "AND"
          }
        ]
      },
      {
        "value": "HVCDPC",
        "criteria": []
      }
    ],
    "sizeRules": [
      {
        "value": "24",
        "criteria": []
      }
    ],
    "labelRules": [],
    "tooltipRules": [
      {
        "value": "'<strong>'+context.feature.properties.pucId+' '+translate.instant(context.feature.properties.objectCode)+'</strong><p class=\"tooltip-line\">'+context.feature.properties.code+'</p><p class=\"tooltip-line\"> '+translate.instant(context.feature.properties.status)+'</p><p class=\"tooltip-line\"> '+translate.instant('HV Grid')+'</p>'",
        "criteria": []
      }
    ],
    "menuHeaderDataRules": []
  },
  {
    "classIds": "HVCDPG",
    "styles": [
      {
        "styleId": "TEMPLATE",
        "styleType": "POINT",
        "description": "HVCDPG_TEMPLATE",
        "defaultStyle": false,
        "attributes": [
          { "name": "classTemplate", "value": "true" }
        ],
        "iconUrl": "assets/app/img/map-markers/puc/CL_BT_NODE_7/nodo-consegna-BP603.svg",
        "color": "#FF0000"
      },
      {
        "styleId": "SEARCH_TEMPLATE",
        "styleType": "POINT",
        "description": "SEARCH_TEMPLATE",
        "defaultStyle": false,
        "attributes": [
          { "name": "searchClassTemplate", "value": "true" }
        ],
        "iconUrl": "assets/app/img/map-markers/puc/CL_BT_NODE_7/nodo-consegna-BP603.svg",
        "color": "#FFFFFF"
      },
      {
        "styleId": "HVCDPG",
        "styleType": "POINT",
        "description": "HVCDPG",
        "defaultStyle": false,
        "attributes": [],
        "color": "#ff0000",
        "iconUrl": "assets/app/img/map-markers/puc/CL_BT_NODE_7/nodo-consegna-BP603.svg"
      },
      {
        "styleId": "HVCDPG-dismantled",
        "styleType": "POINT",
        "description": "HVCDPG",
        "defaultStyle": false,
        "attributes": [],
        "color": "yellow",
        "iconUrl": "assets/app/img/map-markers/puc/CL_BT_NODE_7/nodo-consegna-BP603.svg"
      },
      {
        "styleId": "HVCDPG-outOfService",
        "styleType": "POINT",
        "description": "HVCDPG",
        "defaultStyle": false,
        "attributes": [],
        "color": "violet",
        "iconUrl": "assets/app/img/map-markers/puc/CL_BT_NODE_7/nodo-consegna-BP603.svg"
      },
      {
        "styleId": "HVCDPG-editMode",
        "styleType": "POINT",
        "description": "HVCDPG-editMode",
        "defaultStyle": false,
        "attributes": [],
        "color": "#999999",
        "iconUrl": "assets/app/img/map-markers/puc/CL_BT_NODE_7/nodo-consegna-BP603.svg"
      }
    ],
    "styleRules": [
      {
        "value": "HVCDPG-editMode",
        "criteria": [
          {
            "field": "properties.editMode",
            "value": "true",
            "fieldType": "string",
            "operator": "=",
            "criteriaOperator": "AND"
          }
        ]
      },
      {
        "value": "HVCDPG-dismantled",
        "criteria": [
          {
            "field": "properties.objectFormStatusIdPrefix",
            "value": "39",
            "fieldType": "number",
            "operator": "=",
            "criteriaOperator": "AND"
          }
        ]
      },
      {
        "value": "HVCDPG-outOfService",
        "criteria": [
          {
            "field": "properties.objectFormStatusIdPrefix",
            "value": "41",
            "fieldType": "number",
            "operator": "=",
            "criteriaOperator": "AND"
          }
        ]
      },
      {
        "value": "HVCDPG",
        "criteria": []
      }
    ],
    "sizeRules": [
      {
        "value": "24",
        "criteria": []
      }
    ],
    "labelRules": [],
    "tooltipRules": [
      {
        "value": "'<strong>'+context.feature.properties.pucId+' '+translate.instant(context.feature.properties.objectCode)+'</strong><p class=\"tooltip-line\">'+context.feature.properties.code+'</p><p class=\"tooltip-line\"> '+translate.instant(context.feature.properties.status)+'</p><p class=\"tooltip-line\"> '+translate.instant('HV Grid')+'</p>'",
        "criteria": []
      }
    ],
    "menuHeaderDataRules": []
  },
  {
    "classIds": "HVCDPT",
    "styles": [
      {
        "styleId": "TEMPLATE",
        "styleType": "POINT",
        "description": "HVCDPT_TEMPLATE",
        "defaultStyle": false,
        "attributes": [
          { "name": "classTemplate", "value": "true" }
        ],
        "iconUrl": "assets/app/img/map-markers/puc/CL_BT_NODE_7/nodo-consegna-BP604.svg",
        "color": "#FF0000"
      },
      {
        "styleId": "SEARCH_TEMPLATE",
        "styleType": "POINT",
        "description": "SEARCH_TEMPLATE",
        "defaultStyle": false,
        "attributes": [
          { "name": "searchClassTemplate", "value": "true" }
        ],
        "iconUrl": "assets/app/img/map-markers/puc/CL_BT_NODE_7/nodo-consegna-BP604.svg",
        "color": "#FFFFFF"
      },
      {
        "styleId": "HVCDPT",
        "styleType": "POINT",
        "description": "HVCDPT",
        "defaultStyle": false,
        "attributes": [],
        "color": "#ff0000",
        "iconUrl": "assets/app/img/map-markers/puc/CL_BT_NODE_7/nodo-consegna-BP604.svg"
      },
      {
        "styleId": "HVCDPT-dismantled",
        "styleType": "POINT",
        "description": "HVCDPT",
        "defaultStyle": false,
        "attributes": [],
        "color": "yellow",
        "iconUrl": "assets/app/img/map-markers/puc/CL_BT_NODE_7/nodo-consegna-BP604.svg"
      },
      {
        "styleId": "HVCDPT-outOfService",
        "styleType": "POINT",
        "description": "HVCDPT",
        "defaultStyle": false,
        "attributes": [],
        "color": "violet",
        "iconUrl": "assets/app/img/map-markers/puc/CL_BT_NODE_7/nodo-consegna-BP604.svg"
      },
      {
        "styleId": "HVCDPT-editMode",
        "styleType": "POINT",
        "description": "HVCDPT-editMode",
        "defaultStyle": false,
        "attributes": [],
        "color": "#999999",
        "iconUrl": "assets/app/img/map-markers/puc/CL_BT_NODE_7/nodo-consegna-BP604.svg"
      }
    ],
    "styleRules": [
      {
        "value": "HVCDPT-editMode",
        "criteria": [
          {
            "field": "properties.editMode",
            "value": "true",
            "fieldType": "string",
            "operator": "=",
            "criteriaOperator": "AND"
          }
        ]
      },
      {
        "value": "HVCDPT-dismantled",
        "criteria": [
          {
            "field": "properties.objectFormStatusIdPrefix",
            "value": "39",
            "fieldType": "number",
            "operator": "=",
            "criteriaOperator": "AND"
          }
        ]
      },
      {
        "value": "HVCDPT-outOfService",
        "criteria": [
          {
            "field": "properties.objectFormStatusIdPrefix",
            "value": "41",
            "fieldType": "number",
            "operator": "=",
            "criteriaOperator": "AND"
          }
        ]
      },
      {
        "value": "HVCDPT",
        "criteria": []
      }
    ],
    "sizeRules": [
      {
        "value": "24",
        "criteria": []
      }
    ],
    "labelRules": [],
    "tooltipRules": [
      {
        "value": "'<strong>'+context.feature.properties.pucId+' '+translate.instant(context.feature.properties.objectCode)+'</strong><p class=\"tooltip-line\">'+context.feature.properties.code+'</p><p class=\"tooltip-line\"> '+translate.instant(context.feature.properties.status)+'</p><p class=\"tooltip-line\"> '+translate.instant('HV Grid')+'</p>'",
        "criteria": []
      }
    ],
    "menuHeaderDataRules": []
  },
  {
    "classIds": "HVCDPD",
    "styles": [
      {
        "styleId": "TEMPLATE",
        "styleType": "POINT",
        "description": "HVCDPD_TEMPLATE",
        "defaultStyle": false,
        "attributes": [
          { "name": "classTemplate", "value": "true" }
        ],
        "iconUrl": "assets/app/img/map-markers/puc/CL_BT_NODE_7/nodo-consegna-BP605.svg",
        "color": "#FF0000"
      },
      {
        "styleId": "SEARCH_TEMPLATE",
        "styleType": "POINT",
        "description": "SEARCH_TEMPLATE",
        "defaultStyle": false,
        "attributes": [
          { "name": "searchClassTemplate", "value": "true" }
        ],
        "iconUrl": "assets/app/img/map-markers/puc/CL_BT_NODE_7/nodo-consegna-BP605.svg",
        "color": "#FFFFFF"
      },
      {
        "styleId": "HVCDPD",
        "styleType": "POINT",
        "description": "HVCDPD",
        "defaultStyle": false,
        "attributes": [],
        "color": "#ff0000",
        "iconUrl": "assets/app/img/map-markers/puc/CL_BT_NODE_7/nodo-consegna-BP605.svg"
      },
      {
        "styleId": "HVCDPD-dismantled",
        "styleType": "POINT",
        "description": "HVCDPD",
        "defaultStyle": false,
        "attributes": [],
        "color": "yellow",
        "iconUrl": "assets/app/img/map-markers/puc/CL_BT_NODE_7/nodo-consegna-BP605.svg"
      },
      {
        "styleId": "HVCDPD-outOfService",
        "styleType": "POINT",
        "description": "HVCDPD",
        "defaultStyle": false,
        "attributes": [],
        "color": "violet",
        "iconUrl": "assets/app/img/map-markers/puc/CL_BT_NODE_7/nodo-consegna-BP605.svg"
      },
      {
        "styleId": "HVCDPD-editMode",
        "styleType": "POINT",
        "description": "HVCDPD-editMode",
        "defaultStyle": false,
        "attributes": [],
        "color": "#999999",
        "iconUrl": "assets/app/img/map-markers/puc/CL_BT_NODE_7/nodo-consegna-BP605.svg"
      }
    ],
    "styleRules": [
      {
        "value": "HVCDPD-editMode",
        "criteria": [
          {
            "field": "properties.editMode",
            "value": "true",
            "fieldType": "string",
            "operator": "=",
            "criteriaOperator": "AND"
          }
        ]
      },
      {
        "value": "HVCDPD-dismantled",
        "criteria": [
          {
            "field": "properties.objectFormStatusIdPrefix",
            "value": "39",
            "fieldType": "number",
            "operator": "=",
            "criteriaOperator": "AND"
          }
        ]
      },
      {
        "value": "HVCDPD-outOfService",
        "criteria": [
          {
            "field": "properties.objectFormStatusIdPrefix",
            "value": "41",
            "fieldType": "number",
            "operator": "=",
            "criteriaOperator": "AND"
          }
        ]
      },
      {
        "value": "HVCDPD",
        "criteria": []
      }
    ],
    "sizeRules": [
      {
        "value": "24",
        "criteria": []
      }
    ],
    "labelRules": [],
    "tooltipRules": [
      {
        "value": "'<strong>'+context.feature.properties.pucId+' '+translate.instant(context.feature.properties.objectCode)+'</strong><p class=\"tooltip-line\">'+context.feature.properties.code+'</p><p class=\"tooltip-line\"> '+translate.instant(context.feature.properties.status)+'</p><p class=\"tooltip-line\"> '+translate.instant('HV Grid')+'</p>'",
        "criteria": []
      }
    ],
    "menuHeaderDataRules": []
  },
  {
    "classIds": "HVLSAN",
    "styles": [
      {
        "styleId": "TEMPLATE",
        "styleType": "LINE",
        "description": "HVLSAN_TEMPLATE",
        "defaultStyle": false,
        "attributes": [
          { "name": "classTemplate", "value": "true" }
        ],
        "iconUrl": "assets/app/img/map-markers/puc/LINE/line.svg",
        "weight": 2,
        "color": "#FF0000"
      },
      {
        "styleId": "SEARCH_TEMPLATE",
        "styleType": "LINE",
        "description": "SEARCH_TEMPLATE",
        "defaultStyle": false,
        "attributes": [
          { "name": "searchClassTemplate", "value": "true" }
        ],
        "iconUrl": "assets/app/img/map-markers/puc/LINE/line.svg",
        "weight": 2,
        "color": "#FFFFFF"
      },
      {
        "styleId": "HVLSAN",
        "styleType": "LINE",
        "description": "HVLSAN",
        "defaultStyle": false,
        "attributes": [],
        "color": "#ff0000",
        "weight": 2
      },
      {
        "styleId": "HVLSAN-editMode",
        "styleType": "LINE",
        "description": "HVLSAN-editMode",
        "defaultStyle": false,
        "attributes": [],
        "color": "#999999",
        "weight": 2
      },
      {
        "styleId": "HVLSAN-dismantled",
        "styleType": "LINE",
        "description": "HVLSAN-dismantled",
        "defaultStyle": false,
        "attributes": [],
        "color": "yellow",
        "weight": 2
      },
      {
        "styleId": "HVLSAN-outOfService",
        "styleType": "LINE",
        "description": "HVLSAN-outOfService",
        "defaultStyle": false,
        "attributes": [],
        "color": "violet",
        "weight": 2
      }
    ],
    "styleRules": [
      {
        "value": "HVLSAN-editMode",
        "criteria": [
          {
            "field": "properties.editMode",
            "value": "true",
            "fieldType": "string",
            "operator": "=",
            "criteriaOperator": "AND"
          }
        ]
      },
      {
        "value": "HVLSAN-dismantled",
        "criteria": [
          {
            "field": "properties.objectFormStatusIdPrefix",
            "value": "39",
            "fieldType": "number",
            "operator": "=",
            "criteriaOperator": "AND"
          }
        ]
      },
      {
        "value": "HVLSAN-outOfService",
        "criteria": [
          {
            "field": "properties.objectFormStatusIdPrefix",
            "value": "41",
            "fieldType": "number",
            "operator": "=",
            "criteriaOperator": "AND"
          }
        ]
      },
      {
        "value": "HVLSAN",
        "criteria": []
      }
    ],
    "sizeRules": [],
    "labelRules": [],
    "tooltipRules": [
      {
        "value": "'<strong>'+context.feature.properties.pucId+' '+translate.instant(context.feature.properties.objectCode)+'</strong><p class=\"tooltip-line\">'+context.feature.properties.code+'</p><p class=\"tooltip-line\"> '+translate.instant(context.feature.properties.status)+'</p><p class=\"tooltip-line\"> '+translate.instant('HV Grid')+'</p>'",
        "criteria": []
      }
    ],
    "menuHeaderDataRules": []
  },
  {
    "classIds": "HVLSAC",
    "styles": [
      {
        "styleId": "TEMPLATE",
        "styleType": "LINE",
        "description": "HVLSAC_TEMPLATE",
        "defaultStyle": false,
        "attributes": [
          { "name": "classTemplate", "value": "true" }
        ],
        "iconUrl": "assets/app/img/map-markers/puc/LINE/line.svg",
        "weight": 2,
        "dashArray": "5,4,1,4",
        "color": "#FF0000"
      },
      {
        "styleId": "SEARCH_TEMPLATE",
        "styleType": "LINE",
        "description": "SEARCH_TEMPLATE",
        "defaultStyle": false,
        "attributes": [
          { "name": "searchClassTemplate", "value": "true" }
        ],
        "iconUrl": "assets/app/img/map-markers/puc/LINE/line.svg",
        "weight": 2,
        "dashArray": "5,4,1,4",
        "color": "#FFFFFF"
      },
      {
        "styleId": "HVLSAC",
        "styleType": "LINE",
        "description": "HVLSAC",
        "defaultStyle": false,
        "attributes": [],
        "color": "#ff0000",
        "weight": 2,
        "dashArray": "5,4,1,4"
      },
      {
        "styleId": "HVLSAC-editMode",
        "styleType": "LINE",
        "description": "HVLSAC-editMode",
        "defaultStyle": false,
        "attributes": [],
        "color": "#999999",
        "weight": 2,
        "dashArray": "5,4,1,4"
      },
      {
        "styleId": "HVLSAC-dismantled",
        "styleType": "LINE",
        "description": "HVLSAC-dismantled",
        "defaultStyle": false,
        "attributes": [],
        "color": "yellow",
        "weight": 2,
        "dashArray": "5,4,1,4"
      },
      {
        "styleId": "HVLSAC-outOfService",
        "styleType": "LINE",
        "description": "HVLSAC-outOfService",
        "defaultStyle": false,
        "attributes": [],
        "color": "violet",
        "weight": 2,
        "dashArray": "5,4,1,4"
      }
    ],
    "styleRules": [
      {
        "value": "HVLSAC-editMode",
        "criteria": [
          {
            "field": "properties.editMode",
            "value": "true",
            "fieldType": "string",
            "operator": "=",
            "criteriaOperator": "AND"
          }
        ]
      },
      {
        "value": "HVLSAC-dismantled",
        "criteria": [
          {
            "field": "properties.objectFormStatusIdPrefix",
            "value": "39",
            "fieldType": "number",
            "operator": "=",
            "criteriaOperator": "AND"
          }
        ]
      },
      {
        "value": "HVLSAC-outOfService",
        "criteria": [
          {
            "field": "properties.objectFormStatusIdPrefix",
            "value": "41",
            "fieldType": "number",
            "operator": "=",
            "criteriaOperator": "AND"
          }
        ]
      },
      {
        "value": "HVLSAC",
        "criteria": []
      }
    ],
    "sizeRules": [],
    "labelRules": [],
    "tooltipRules": [
      {
        "value": "'<strong>'+context.feature.properties.pucId+' '+translate.instant(context.feature.properties.objectCode)+'</strong><p class=\"tooltip-line\">'+context.feature.properties.code+'</p><p class=\"tooltip-line\"> '+translate.instant(context.feature.properties.status)+'</p><p class=\"tooltip-line\"> '+translate.instant('HV Grid')+'</p>'",
        "criteria": []
      }
    ],
    "menuHeaderDataRules": []
  },
  {
    "classIds": "HVLSUC",
    "styles": [
      {
        "styleId": "TEMPLATE",
        "styleType": "LINE",
        "description": "HVLSUC_TEMPLATE",
        "defaultStyle": false,
        "attributes": [
          { "name": "classTemplate", "value": "true" }
        ],
        "iconUrl": "assets/app/img/map-markers/puc/LINE/line.svg",
        "weight": 2,
        "dashArray": "4,4",
        "color": "#FF0000"
      },
      {
        "styleId": "SEARCH_TEMPLATE",
        "styleType": "LINE",
        "description": "SEARCH_TEMPLATE",
        "defaultStyle": false,
        "attributes": [
          { "name": "searchClassTemplate", "value": "true" }
        ],
        "iconUrl": "assets/app/img/map-markers/puc/LINE/line.svg",
        "weight": 2,
        "dashArray": "4,4",
        "color": "#FFFFFF"
      },
      {
        "styleId": "HVLSUC",
        "styleType": "LINE",
        "description": "HVLSUC",
        "defaultStyle": false,
        "attributes": [],
        "color": "#ff0000",
        "weight": 2,
        "dashArray": "4,4"
      },
      {
        "styleId": "HVLSUC-editMode",
        "styleType": "LINE",
        "description": "HVLSUC-editMode",
        "defaultStyle": false,
        "attributes": [],
        "color": "#999999",
        "weight": 2,
        "dashArray": "4,4"
      },
      {
        "styleId": "HVLSUC-dismantled",
        "styleType": "LINE",
        "description": "HVLSUC-dismantled",
        "defaultStyle": false,
        "attributes": [],
        "color": "yellow",
        "weight": 2,
        "dashArray": "4,4"
      },
      {
        "styleId": "HVLSUC-outOfService",
        "styleType": "LINE",
        "description": "HVLSUC-outOfService",
        "defaultStyle": false,
        "attributes": [],
        "color": "violet",
        "weight": 2,
        "dashArray": "4,4"
      }
    ],
    "styleRules": [
      {
        "value": "HVLSUC-editMode",
        "criteria": [
          {
            "field": "properties.editMode",
            "value": "true",
            "fieldType": "string",
            "operator": "=",
            "criteriaOperator": "AND"
          }
        ]
      },
      {
        "value": "HVLSUC-dismantled",
        "criteria": [
          {
            "field": "properties.objectFormStatusIdPrefix",
            "value": "39",
            "fieldType": "number",
            "operator": "=",
            "criteriaOperator": "AND"
          }
        ]
      },
      {
        "value": "HVLSUC-outOfService",
        "criteria": [
          {
            "field": "properties.objectFormStatusIdPrefix",
            "value": "41",
            "fieldType": "number",
            "operator": "=",
            "criteriaOperator": "AND"
          }
        ]
      },
      {
        "value": "HVLSUC",
        "criteria": []
      }
    ],
    "sizeRules": [],
    "labelRules": [],
    "tooltipRules": [
      {
        "value": "'<strong>'+context.feature.properties.pucId+' '+translate.instant(context.feature.properties.objectCode)+'</strong><p class=\"tooltip-line\">'+context.feature.properties.code+'</p><p class=\"tooltip-line\"> '+translate.instant(context.feature.properties.status)+'</p><p class=\"tooltip-line\"> '+translate.instant('HV Grid')+'</p>'",
        "criteria": []
      }
    ],
    "menuHeaderDataRules": []
  }
]

<> 2025-06-10T144059.200.json
<> 2025-06-10T135839.200.json

###