create sequence layer_rule_criteria_seq start with 1 increment by 50;
create sequence layer_rule_seq start with 1 increment by 50;
create sequence map_layer_style_attribute_seq start with 1 increment by 50;
create sequence map_layer_style_seq start with 1 increment by 50;
create sequence style_definition_seq start with 1 increment by 50;
create table layer_rule (linked boolean, list_order integer, id bigint not null, environment varchar(255), layer_group varchar(255), value TEXT, primary key (id));
create table layer_rule_criteria (list_order integer, id bigint not null, criteria_type varchar(31) not null, criteria_operator varchar(255), field varchar(255), field_type varchar(255), operator varchar(255), rule_ref varchar(255), value varchar(255), primary key (id));
create table map_layer_style (default_style boolean, fill boolean, fill_opacity float(53), stroke boolean, weight float(53), z_index_offset integer, id bigint not null, color varchar(255), dash_array varchar(255), description varchar(255), fill_color varchar(255), icon_data varchar(255), icon_url varchar(255), style_id varchar(255), style_type varchar(255), primary key (id));
create table map_layer_style_attribute (id bigint not null, name varchar(255), value varchar(255), primary key (id));
create table map_layer_style_attributes (attributes_id bigint not null unique, map_layer_style_id bigint not null);
create table rules_criteria (criteria_id bigint not null, rule_id bigint not null);
create table style_definition (id bigint not null, class_ids varchar(255), country varchar(255), environment varchar(255), existing_style_override_mode varchar(255), layer_group varchar(255), tags varchar(255), primary key (id));
create table style_definition_label_rules (label_rules_id bigint not null unique, style_definition_id bigint not null);
create table style_definition_menu_header_data_rules (menu_header_data_rules_id bigint not null unique, style_definition_id bigint not null);
create table style_definition_size_rules (size_rules_id bigint not null unique, style_definition_id bigint not null);
create table style_definition_style_rules (style_definition_id bigint not null, style_rules_id bigint not null unique);
create table style_definition_styles (style_definition_id bigint not null, styles_id bigint not null unique);
create table style_definition_tooltip_rules (style_definition_id bigint not null, tooltip_rules_id bigint not null unique);
alter table if exists map_layer_style_attributes add constraint FKft7qqyq2i84d1thalsu4xy972 foreign key (attributes_id) references map_layer_style_attribute;
alter table if exists map_layer_style_attributes add constraint FKfsfswjh9pr7py6y7c95fd4mhj foreign key (map_layer_style_id) references map_layer_style;
alter table if exists rules_criteria add constraint FK2w6hr9w0nquurveifjq3j6q0 foreign key (criteria_id) references layer_rule_criteria;
alter table if exists rules_criteria add constraint FKd58f4asuav171j493ndryywa7 foreign key (rule_id) references layer_rule;
alter table if exists style_definition_label_rules add constraint FKa1melf1bcasbp7hj8of4p13s3 foreign key (label_rules_id) references layer_rule;
alter table if exists style_definition_label_rules add constraint FKirtmwv5w9vjo4f5vvhrx4akiv foreign key (style_definition_id) references style_definition;
alter table if exists style_definition_menu_header_data_rules add constraint FKneyralw27ppkyxlm4uwytfc6k foreign key (menu_header_data_rules_id) references layer_rule;
alter table if exists style_definition_menu_header_data_rules add constraint FKj4bjfuoa7b0slsfj3a1l5hjy1 foreign key (style_definition_id) references style_definition;
alter table if exists style_definition_size_rules add constraint FKc9rhfcf6vt73gg3cw38dwby4c foreign key (size_rules_id) references layer_rule;
alter table if exists style_definition_size_rules add constraint FKm003e0c34bsdy65j8lcn9imaa foreign key (style_definition_id) references style_definition;
alter table if exists style_definition_style_rules add constraint FKiotkpem6u346veuea8vue4gli foreign key (style_rules_id) references layer_rule;
alter table if exists style_definition_style_rules add constraint FKkiq1tfe11fvu4fk9p3bd5whmb foreign key (style_definition_id) references style_definition;
alter table if exists style_definition_styles add constraint FKmscp2vbfac7gh1kmn6d2t4e7t foreign key (styles_id) references map_layer_style;
alter table if exists style_definition_styles add constraint FK1jij5ihk1pe31y1iiob2x8e2i foreign key (style_definition_id) references style_definition;
alter table if exists style_definition_tooltip_rules add constraint FKgk1u2060e88ggpcuo2nrh3ils foreign key (tooltip_rules_id) references layer_rule;
alter table if exists style_definition_tooltip_rules add constraint FK7rmhqlracpc5y2su4letnl143 foreign key (style_definition_id) references style_definition;
